import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar'
import MyProfilePic from './components/MyProfilePic'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Kristians blog',
  description: 'Generated by Nils-Kristian Pedersen',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='dark:bg-slate-800'>
      <body className={inter.className}>
        <Navbar />
        <MyProfilePic />
        {children}</body>
    </html>
  )
}
